name: NodeJS CI with paketo-buildpacks/web-servers

# Controls when the workflow will run (EVENTS)
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:

      # Setup Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: '20.15.0'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: https://gitea.com/actions/checkout@v4

      - name: Install pack cli (buildpacks)
        run: |
            sudo add-apt-repository ppa:cncf-buildpacks/pack-cli -yy
            sudo apt-get update -yy
            sudo apt-get install pack-cli -yy

      - name: Build and push container image to registry
        run: |
            pack build --buildpack paketo-buildpacks/web-servers \
            --builder paketobuildpacks/builder-jammy-base \
            --env "BP_WEB_SERVER=nginx" \ 
            --env "BP_WEB_SERVER_ROOT=dist" \
            --env "BP_WEB_SERVER_ENABLE_PUSH_STATE=true" \
            --env "NODE_ENV=production" \ 
            registry.moglidev.xyz/my-family-net-app:dev-1.0

      - name: Loging & Push to MogliDev (Registry) Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push registry.moglidev.xyz/my-family-net-app:dev-1.0