name: NodeJS CI with buildx (Multi-arch)

# Controls when the workflow will run (EVENTS)
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "buildXBased" ]
  pull_request:
    branches: [ "buildXBased" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKER_HUB_REG }}/my-family-net-app

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get APP version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3        

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_HUB_REG }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push to MogliDev Registry (Multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_REG }}/my-family-net-app:latest , ${{ secrets.DOCKER_HUB_REG }}/my-family-net-app:${{env.APP_VERSION}}
          build-args: |
            FAMLIYNET_KEYCLOAK_URL=${{vars.FAMLIYNET_KEYCLOAK_URL}}
            FAMLIYNET_KEYCLOAK_REALM=${{vars.FAMLIYNET_KEYCLOAK_REALM}}
            FAMLIYNET_KEYCLOAK_CLIENT_ID=${{vars.FAMLIYNET_KEYCLOAK_CLIENT_ID}}
          

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKER_HUB_REG }}/my-family-net-app:${{ env.APP_VERSION }}
